name: Gree HVAC MQTT Bridge
version: 2.0.0
slug: gree_hvac_mqtt_bridge
description: Control Gree air conditioners through MQTT with Home Assistant MQTT Discovery.
url: https://github.com/aretokas/gree-hvac-mqtt-bridge
image: ghcr.io/aretokas/{arch}-gree-hvac-mqtt-bridge
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
boot: auto
init: false
options:
  mqtt:
    broker_url: mqtt://localhost
    username: ""
    password: ""
    retain: true
    discovery_prefix: homeassistant
    debug: false
  devices:
    - hvac_host: 192.168.1.255
      auto_lights: true
      auto_xfan: true
      recovery_interval: 30
      mqtt_topic_prefix: greehvac
schema:
  mqtt:
    broker_url: url
    username: str?
    password: password?
    retain: bool?
    discovery_prefix: str?
    debug: bool?
  devices:
    - hvac_host: str
      auto_lights: bool?
      auto_xfan: bool?
      recovery_interval: int?
      mqtt_topic_prefix: str
      zigbee2mqtt_sensor_topic: str?
